definitions:
  entities.Rocket:
    properties:
      eventCursor:
        type: integer
      id:
        type: string
      launchDate:
        type: string
      mission:
        type: string
      rocketType:
        type: string
      speed:
        $ref: '#/definitions/entities.RocketSpeed'
      status:
        $ref: '#/definitions/entities.RocketStatus'
    type: object
  entities.RocketSpeed:
    properties:
      current:
        type: number
      max:
        type: number
    type: object
  entities.RocketStatus:
    properties:
      active:
        type: boolean
      reason:
        type: string
    type: object
info:
  contact: {}
paths:
  /messages:
    post:
      description: returns string
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            type: string
        "422":
          description: Unprocessable Entity
          schema:
            type: string
      summary: Receive Rocket status messages
      tags:
      - MessageService
  /rocket:
    get:
      description: returns instance of rocket
      parameters:
      - description: id
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.Rocket'
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Return a rocket by id
      tags:
      - RocketService
  /rockets:
    get:
      description: returns array of rockets
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entities.Rocket'
            type: array
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Returns all rockets
      tags:
      - RocketService
swagger: "2.0"
