info:
  contact: {}
paths:
  /messages:
    post:
      description: returns string
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            type: string
        "422":
          description: Unprocessable Entity
          schema:
            type: string
      summary: Receive Rocket status messages
      tags:
      - MessageService
swagger: "2.0"
